services:
  data_load:
    build:
      context: .
      dockerfile: docker/data_load/Dockerfile
    container_name: oda-data-load
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./storage:/app/storage
      - ./reports:/app/reports
    networks:
      - app_network

  data_quality_analysis:
    build:
      context: .
      dockerfile: docker/data_quality_analysis/Dockerfile
    container_name: oda-data-quality
    env_file:
      - .env
    depends_on:
      - data_load
    volumes:
      - ./data:/app/data
      - ./storage:/app/storage
      - ./reports:/app/reports
    networks:
      - app_network

  data_research:
    build:
      context: .
      dockerfile: docker/data_research/Dockerfile
    container_name: oda-data-research
    env_file:
      - .env
    depends_on:
      - data_load
    volumes:
      - ./data:/app/data
      - ./storage:/app/storage
      - ./reports:/app/reports
    networks:
      - app_network

  visualization:
    build:
      context: .
      dockerfile: docker/visualization/Dockerfile
    container_name: oda-visualization
    env_file:
      - .env
    depends_on:
      - data_load
    volumes:
      - ./data:/app/data
      - ./storage:/app/storage
      - ./plots:/app/plots
    networks:
      - app_network

  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    container_name: oda-web
    env_file:
      - .env
    depends_on:
      - data_quality_analysis
      - data_research
      - visualization
    ports:
      - "${WEB_PORT}:8000"
    volumes:
      - ./reports:/app/reports
      - ./plots:/app/plots
      - ./storage:/app/storage
      - ./data:/app/data
    networks:
      - app_network

networks:
  app_network:
    driver: bridge